name: aves
description: A visual media gallery and metadata explorer app.
repository: https://github.com/deckerst/aves
version: 1.13.10+161
publish_to: none

environment:
  flutter: 3.27.4
  sdk: ">=3.6.0 <4.0.0"
workspace:
  - plugins/aves_magnifier
  - plugins/aves_map
  - plugins/aves_model
  - plugins/aves_report
  - plugins/aves_report_crashlytics
  - plugins/aves_screen_state
  - plugins/aves_services
  - plugins/aves_services_google
  - plugins/aves_ui
  - plugins/aves_utils
  - plugins/aves_video
  - plugins/aves_video_mpv

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aves_magnifier:
    path: plugins/aves_magnifier
  aves_map:
    path: plugins/aves_map
  aves_model:
    path: plugins/aves_model
  aves_report:
    path: plugins/aves_report
  aves_report_platform:
    path: plugins/aves_report_crashlytics
  aves_screen_state:
    path: plugins/aves_screen_state
  aves_services:
    path: plugins/aves_services
  aves_services_platform:
    path: plugins/aves_services_google
  aves_video:
    path: plugins/aves_video
  aves_video_mpv:
    path: plugins/aves_video_mpv
  aves_ui:
    path: plugins/aves_ui
  aves_utils:
    path: plugins/aves_utils
  charts_flutter:
    git:
      url: https://github.com/deckerst/flutter_google_charts.git
      ref: aves
      path: charts_flutter
  collection:
  connectivity_plus:
  country_code:
  csv:
  decorated_icon:
  device_info_plus:
  dlna_dart:
  dynamic_color: 1.7.0
  equatable:
  event_bus:
  expansion_tile_card:
    git:
      url: https://github.com/deckerst/expansion_tile_card.git
  flex_color_picker:
  floating:
  fluster:
  flutter_displaymode:
  flutter_highlight:
  flutter_localizations_plus:
    git:
      url: https://github.com/deckerst/flutter_localizations_plus.git
      ref: 6a8c14bceaefd00e703ad517fd2a32fa2081b5de
  flutter_map:
  flutter_markdown_plus:
  flutter_staggered_animations:
  get_it:
  # OCR Dependencies
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_commons: ^0.7.0
  gpx:
  http:
  intl:
  latlong2:
  leak_tracker:
  local_auth:
  material_design_icons_flutter:
  material_symbols_icons:
  network_info_plus:
  overlay_support:
  package_info_plus:
  palette_generator:
  panorama:
    git:
      url: https://github.com/deckerst/aves_panorama.git
      ref: aves
  path:
  pattern_lock:
  pdf:
  percent_indicator:
  permission_handler:
  pin_code_fields:
  printing:
  proj4dart:
  provider:
  screen_brightness:
  shared_preferences:
  shelf:
  smooth_page_indicator:
  sqflite:
  stack_trace:
  streams_channel:
    git:
      url: https://github.com/deckerst/aves_streams_channel.git
  synchronized:
  url_launcher:
  vector_map_tiles: ^9.0.0-beta.8
  vector_math:
  vector_tile_renderer:
  volume_controller:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints:
  shared_preferences_platform_interface:
  test:

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true
