name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Keystore and print base64
      run: |
        keytool -genkeypair -alias my_alias -keyalg RSA -keysize 2048 -validity 10000 -keystore my-release-key.jks -storepass pass1234 -keypass pass1234 -dname "CN=GitHub Actions, OU=DevOps, O=MyCompany, L=City, ST=State, C=Country"
        base64 my-release-key.jks
      shell: bash
